[build]
builder = "nixpacks"
buildCommand = "cd src/backend && npx prisma generate --schema=prisma/schema.prisma && npx prisma generate --schema=prisma/master.prisma && npm run build"

[deploy]
startCommand = "cd src/backend && npx prisma migrate deploy --schema=prisma/master.prisma && node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
